### ISSUE TITLE
Where is the dataset downloaded?

### ISSUE THREAD

**Issue by usernamehao** [Eli1995CS/ConvMF#2]

**Comment by Ming2018ming** [comment]
Hello, I'm looking at in-depth learning recently. I'm glad to have read your code. The data set has not been found. If you can provide the following data set, I would be very grateful.

**Comment by lileipisces** [comment]
There are many publicly available review datasets, such as [Yelp ](https://www.yelp.com/dataset/challenge) and [Amazon](http://jmcauley.ucsd.edu/data/amazon/). You can download them from their official websites. Note that, the input data need to be prepared in the right format that I have described in the README document.
